/* OrgLens frontend. Key never enters browser code. */
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let analysis = null;
let currentTab = 'lost_functions';
let token = sessionStorage.getItem('orglens_token') || '';
const DEMO_BEFORE = `1. Департамент клиентского сервиса включает Отдел обращений и Отдел контроля качества.\n2. Отдел обращений принимает обращения клиентов, регистрирует запросы и передаёт ответы заявителям.\n3. Отдел контроля качества ежемесячно оценивает сроки закрытия жалоб и подготавливает отчёт руководству.\n4. ИТ-департамент отвечает за поддержку информационных систем и управление инцидентами.\n5. Отдел закупок проводит конкурсные процедуры и ведёт реестр договоров.`;
const DEMO_AFTER = `1. Управление клиентского опыта включает Группу обращений и Группу цифрового сервиса.\n2. Группа обращений принимает обращения клиентов, регистрирует запросы и передаёт ответы заявителям.\n3. Группа цифрового сервиса внедряет электронную очередь и анализирует пользовательский опыт.\n4. ИТ-департамент обеспечивает поддержку информационных систем и управление инцидентами.\n5. Управление клиентского опыта формирует отчёт по срокам обработки обращений.\n6. Группа цифрового сервиса также формирует отчёт по срокам обработки обращений.\n7. Отдел закупок проводит конкурсные процедуры и ведёт реестр договоров.`;
function showError(t){$('#error').textContent=t;$('#error').classList.remove('hidden');$('#error').scrollIntoView({block:'nearest',behavior:'smooth'})}
function clearError(){$('#error').classList.add('hidden')}
function setStatus(t){$('#sideStatus').textContent=t}
function resetLoading(){ $('#loading').classList.add('hidden');$('#runBtn').disabled=false;$('#runBtn').innerHTML='✳ Запустить ИИ-анализ <span>→</span>'; if(!analysis)$('#empty').classList.remove('hidden') }
function opts(extra={}){return {...extra,headers:{...(token?{'X-OrgLens-Token':token}:{}),...(extra.headers||{})}}}
async function api(url,params){const res=await fetch(url,opts(params));if(res.status===401){let t=prompt('Введите токен доступа OrgLens для этого сервера:');if(t){token=t;sessionStorage.setItem('orglens_token',token);return api(url,params)}throw Error('Доступ ограничен токеном сервера.')}let obj=await res.json().catch(()=>({}));if(!res.ok)throw Error(obj.error||`Ошибка HTTP ${res.status}`);return obj}
async function checkHealth(){try{let h=await api('/api/health');setStatus(h.ai_ready?`OpenAI подключён · ${h.model}`:'Нет OPENAI_API_KEY');}catch(e){setStatus('Сервер недоступен')}}
$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{let id=b.dataset.scroll;document.getElementById(id).scrollIntoView({behavior:'smooth'});$$('.nav-link').forEach(n=>n.classList.toggle('active',n===b))}));
$('#heroStart').onclick=()=>$('#workspace').scrollIntoView({behavior:'smooth'});
$('#demoBtn').onclick=()=>{$('#beforeText').value=DEMO_BEFORE;$('#afterText').value=DEMO_AFTER;$$('.upload-card details').forEach(d=>d.open=true);$('#workspace').scrollIntoView({behavior:'smooth'});clearError()};
for(const side of ['before','after']){$(`#${side}File`).addEventListener('change',e=>{$(`#${side}Names`).textContent=[...e.target.files].map(f=>f.name).join(' · ')||'Файлы не выбраны'})}
const sectionNames={lost_functions:'ВОЗМОЖНАЯ ПОТЕРЯ',duplicate_functions:'ПЕРЕСЕЧЕНИЕ',structure_changes:'ИЗМЕНЕНИЕ',new_functions:'НОВАЯ ФУНКЦИЯ',recommendations:'ДЕЙСТВИЕ'};
function node(tag,cl,txt){let x=document.createElement(tag);if(cl)x.className=cl;if(txt!==undefined)x.textContent=txt;return x}
function renderFindings(kind){currentTab=kind;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===kind));let list=$('#findingList');list.replaceChildren();let findings=analysis[kind]||[];if(!findings.length){list.append(node('div','no-findings','Подтверждённых наблюдений в этой категории не найдено. Это не гарантия отсутствия рисков.'));return}findings.forEach((f,i)=>{let card=node('article','finding'),head=node('div','finding-head'),count=node('span','finding-num',`${sectionNames[kind]} ${String(i+1).padStart(2,'0')}`),body=node('div');body.append(node('h3','',f.title),node('p','',f.explanation));head.append(count,body);card.append(head);let evid=[...(f.before_ids||[]),...(f.after_ids||[])].map(id=>({id,src:analysis.evidence[id]})).filter(e=>e.src);if(evid.length){card.append(node('div','source-title','ПОДТВЕРЖДЕНИЯ ИЗ ПЕРВОИСТОЧНИКОВ'));let area=node('div','evidence-list');evid.forEach(({id,src})=>{let ev=node('div','evidence '+(id.startsWith('A')?'after':''));ev.append(node('b','',`${id.startsWith('B')?'ДО':'ПОСЛЕ'} · ${src.source} · ${src.locator} [${id}]`),node('span','',src.text));area.append(ev)});card.append(area)}list.append(card)})}
$$('[data-tab]').forEach(b=>b.onclick=()=>analysis&&renderFindings(b.dataset.tab));
function renderReport(){let m=analysis.meta;$('#metricBefore').textContent=m.before_segments;$('#metricAfter').textContent=m.after_segments;$('#metricRisks').textContent=analysis.lost_functions.length+analysis.duplicate_functions.length;$('#metricChanges').textContent=analysis.structure_changes.length;$('#summary').textContent=analysis.summary;let map={countLost:'lost_functions',countDuplicate:'duplicate_functions',countStructure:'structure_changes',countNew:'new_functions',countRecommendations:'recommendations'};Object.entries(map).forEach(([id,k])=>$('#'+id).textContent=analysis[k].length);$('#warning').classList.toggle('hidden',!m.truncated);$('#warning').textContent=m.truncated?'Внимание: документы частично сокращены до лимита анализа. Результаты не охватывают полный комплект. Разделите документы на несколько анализов.':'';$('#empty').classList.add('hidden');$('#loading').classList.add('hidden');$('#report').classList.remove('hidden');$('#printBtn').disabled=false;$('#exportBtn').disabled=false;$('#chatInput').disabled=false;$('#chatSend').disabled=false;renderFindings('lost_functions');$('#results').scrollIntoView({behavior:'smooth'})}
$('#runBtn').onclick=async()=>{clearError();if(!$('#consent').checked){showError('Необходимо согласие на отправку извлечённого текста в OpenAI API.');return}const form=new FormData();for(let side of ['before','after']){let inp=$(`#${side}File`),value=$(`#${side}Text`).value;for(let file of inp.files)form.append(side,file);form.append(side+'_text',value);if(!inp.files.length&&!value.trim()){showError(`Добавьте комплект «${side==='before'?'До':'После'}».`);return}}form.append('consent','yes');let btn=$('#runBtn');btn.disabled=true;btn.textContent='Анализ выполняется…';$('#empty').classList.add('hidden');$('#report').classList.add('hidden');$('#loading').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth'});try{let result=await api('/api/analyze',{method:'POST',body:form});analysis=result;renderReport();$('#messages').append(node('div','bubble bot','Анализ завершён. Что именно вы хотите уточнить?'))}catch(e){showError(e.message);$('#workspace').scrollIntoView({behavior:'smooth'})}finally{resetLoading()}};
$('#chatForm').onsubmit=async e=>{e.preventDefault();if(!analysis)return;let inp=$('#chatInput'),q=inp.value.trim();if(!q)return;inp.value='';$('#messages').append(node('div','bubble user',q));let wait=node('div','bubble bot','Анализирую источники…');$('#messages').append(wait);$('#messages').scrollTop=$('#messages').scrollHeight;$('#chatSend').disabled=true;try{let result=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,consent:$('#consent').checked,analysis})});wait.textContent=result.answer}catch(ex){wait.textContent='Ошибка: '+ex.message}finally{$('#chatSend').disabled=false;$('#messages').scrollTop=$('#messages').scrollHeight}};
$$('[data-ask]').forEach(b=>b.onclick=()=>{if(!analysis){$('#workspace').scrollIntoView({behavior:'smooth'});return}$('#chatInput').value=b.dataset.ask;$('#chatInput').focus()});
function exportJSON(){if(!analysis)return;const blob=new Blob([JSON.stringify(analysis,null,2)],{type:'application/json;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='OrgLens_Analysis.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}$('#exportBtn').onclick=exportJSON;
$('#printBtn').onclick=()=>{if(!analysis)return;const snapshots=Object.keys(sectionNames);let all=[];for(let k of snapshots){all.push(...(analysis[k]||[]).map((f,i)=>({...f,_category:sectionNames[k]})))}let active=currentTab, list=$('#findingList');list.replaceChildren();all.forEach((f,i)=>{let card=node('article','finding');card.append(node('h3','',`${f._category} · ${f.title}`),node('p','',f.explanation));let refs=[...f.before_ids,...f.after_ids];refs.forEach(id=>{let s=analysis.evidence[id];if(s)card.append(node('div','evidence',`${id} · ${s.source} · ${s.locator}: ${s.text}`))});list.append(card)});window.print();renderFindings(active)};
checkHealth();
